escape_character_dict = {
    "&lt;": "<",
    "&gt;": ">",
    "&#61;": "=",
    "&#34;": "\"",
    "&#43;": "+"
}

gender_dict = {
    "kvinne": "f",
    "Kvinne": "f",
    #"k": "Kvinne",
    #"ho": "Kvinne",
    #"Ho": "Kvinne",
    "jente": "f",
    "Jente": "f",
    "kvinne/jente": "f",
    "Kvinne/Jente": "f",
    "Kvinne/Kvinne": "f",

    "Mann": "m",
    "mann": "m",
    "gutt": "m",
    #"m": "Mann",
    "man": "m",
    "Jeg er mann": "m",
    "Boolean(Mann)": "m",
    "Mannan": "m",
    "Gut": "m"
}

uib = "UiB"
ntnu = "NTNU"
uis = "UiS"
hvl = "HvL"
uio = "UiO"
kristiania = "Kristiania"
nmbu = "NMBU"


new_column_names = {
    "Hva er ditt kjønn?": "Gender",
    "Hvilken studielinje/studieprogram går du?": "Studyprogram",
    "Hvilket universitet eller høyskole går du på?": "Institution",
    "Når fullførte du videregående skole?": "GraduateYear",
    "Lærte du å programmere i Python i matematikkfagene?": "LearnedPython",
    "Har du deltatt eller fullført et programmeringskurs ved universitet eller høyskole før denne testen?": "UniversityExperience",
    "Har du fullført noen av disse programfagene?.Informasjonsteknologi 1 (IT1)": "IT1",
    "Har du fullført noen av disse programfagene?.Informasjonsteknologi 2 (IT2)": "IT2",
    "Har du fullført noen av disse programfagene?.Programmering og modellering X": "PMX",
    "Hvilke matematikkfag fullførte du på videregående skole?.1P": "1P",
    "Hvilke matematikkfag fullførte du på videregående skole?.1T": "1T",
    "Hvilke matematikkfag fullførte du på videregående skole?.2P": "2P",
    "Hvilke matematikkfag fullførte du på videregående skole?.S1": "S1",
    "Hvilke matematikkfag fullførte du på videregående skole?.S2": "S2",
    "Hvilke matematikkfag fullførte du på videregående skole?.R1": "R1",
    "Hvilke matematikkfag fullførte du på videregående skole?.R2": "R2", 
    "Har du annen erfaring med programmering utenfor skole?": "OutsideExperience",
    "Hvilken annen erfaring med programmering har du utenfor skole?_1": "Outside1",
    "Hvilken annen erfaring med programmering har du utenfor skole?_2": "Outside2",
    "Hvilken annen erfaring med programmering har du utenfor skole?_3": "Outside3",
    "Hvilken annen erfaring med programmering har du utenfor skole?_4": "Outside4",
    "Hvilken annen erfaring med programmering har du utenfor skole?_5": "Outside5",
    "Hvilken annen erfaring med programmering har du utenfor skole?_6": "Outside6",
    "Hvilken annen erfaring med programmering har du utenfor skole?_7": "Outside7",
    "Hvilken annen erfaring med programmering har du utenfor skole?_8": "Outside8",

    # Tasks
    "Hvilken datatype har variabelen <em><b>a</b></em>?": "datatypes1",
    "Hvilken datatype har variabelen <em><b>b</b></em>?": "datatypes2",
    "Hvilken datatype har variabelen <em><b>c</b></em>?": "datatypes3",
    "Hvilken datatype har variabelen <em><b>d</b></em>?": "datatypes4",
    "Hva er verdien til variabelen <em><b>result</b></em>?": "Operators1",
    "Unnamed: 43": "Operators1_unknown",
    "Hva er verdien til variabelen <em><b>result</b></em>?.1": "Operators2",
    "Unnamed: 45": "Operators2_unknown",
    "Hva er verdien til variabelen <em><b>result</b></em>?.2": "Operators3",
    "Unnamed: 47": "Operators3_unknown",
    "Hva er verdien til variabelen <em><b>n </b></em>etter linje 3 er utført?": "Operators4",
    "Unnamed: 49": "Operators4_unknown",
    "Hva er verdien til variabelen <em><b>n </b></em>etter linje 3 er utført?.1": "Operators5",
    "Unnamed: 51": "Operators5_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 4 er utført?": "Variables1a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 4 er utført?": "Variables1b",
    "Unnamed: 54": "Variables1_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 4 er utført?.1": "Variables2a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 4 er utført?.1": "Variables2b",
    "Unnamed: 57": "Variables2_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 5 er utført?": "Variables3a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 5 er utført?": "Variables3b",
    "Unnamed: 60": "Variables3_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 5 er utført?.1": "Variables4a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 5 er utført?.1": "Variables4b",
    "Unnamed: 63": "Variables4_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 6 er utført?": "Variables5a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 6 er utført?": "Variables5b",
    "Hva er verdien til variabelen <em><b>c </b></em>etter linje 6 er utført?": "Variables5c",
    "Unnamed: 67": "Variables5_unknown",
    "Hva er verdien til variabelen <em><b>a </b></em>etter linje 7 er utført?": "Variables6a",
    "Hva er verdien til variabelen <em><b>b </b></em>etter linje 7 er utført?": "Variables6b",
    "Hva er verdien til variabelen <em><b>c </b></em>etter linje 7 er utført?": "Variables6c",
    "Unnamed: 71": "Variables6_unknown",
    "Hva skrives ut når denne koden kjøres?": "Conditionals1",
    "Hva skrives ut når denne koden kjøres?.1": "Conditionals2",
    "Hva skrives ut når denne koden kjøres?.2": "Conditionals3",
    "Hva skrives ut når denne koden kjøres?.3": "Conditionals4",
    "Hva skrives ut når denne koden kjøres?.4": "Loops1",
    "Unnamed: 101": "Loops1_unknown",
    "Hva skrives ut når denne koden kjøres?.5": "Loops2",
    "Unnamed: 103": "Loops2_unknown",
    "Hva skrives ut når denne koden kjøres?.6": "Loops3",
    "Unnamed: 105": "Loops3_unknown",
    "Hva skrives ut når denne koden kjøres?.7": "Loops4",
    "Unnamed: 107": "Loops4_unknown",
    "Hva skrives ut når denne koden kjøres?.8": "Loops5",
    "Unnamed: 109": "Loops5_unknown",
    "Hva skrives ut når denne koden kjøres?.9": "Loops6",
    "Unnamed: 111": "Loops6_unknown",
    "Hva skrives ut når denne koden kjøres?.10": "Loops7",
    "Unnamed: 113": "Loops7_unknown",
    "Hva skrives ut når denne koden kjøres?.11": "Lists1",
    "Unnamed: 115": "Lists1_unknown",
    "Hva skrives ut når denne koden kjøres?.12": "Lists2",
    "Unnamed: 117": "Lists2_unknown",
    "Hvilke verdier har listen <em><b>a</b></em> etter linje 4 er utført?": "Lists3a",
    "Hvilke verdier har listen <em><b>b</b></em> etter linje 4 er utført?": "Lists3b",
    "Hva skrives ut når denne koden kjøres?.13": "Functions1",
    "Unnamed: 121": "Functions1_unknown",
    "Hva skrives ut når denne koden kjøres?.14": "Functions2",
    "Unnamed: 123": "Functions2_unknown",
    "Hva skrives ut når denne koden kjøres?.15": "Functions3",
    "Unnamed: 125": "Functions3_unknown",
    "Hva skrives ut når denne koden kjøres?.16": "Functions4",
    "Unnamed: 127": "Functions4_unknown",
    "Hva skrives ut når denne koden kjøres?.17": "Functions5",
    "Unnamed: 129": "Functions5_unknown",
    "Hva skrives ut når denne koden kjøres?.18": "Functions6",
    "Unnamed: 131": "Functions6_unknown",
    "Hva skrives ut når denne koden kjøres?.19": "Functions7",
    "Unnamed: 133": "Functions7_unknown",
    "Hva skrives ut når denne koden kjøres?.20": "Functions8",
    "Unnamed: 135": "Functions8_unknown",
    "Hva skrives ut når denne koden kjøres?.21": "Functions9",
    "Unnamed: 137": "Functions9_unknown",
    "Hva synes du om vanskelighetsgraden på denne testen?": "difficulty",
    "Har du noen kommentarer til denne testen?": "comments",
    "$answer_time_ms": "time"
}